# Generated by Django 5.0.3 on 2024-03-12 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('FirstName', models.CharField(max_length=20)),
                ('LastName', models.CharField(max_length=20)),
                ('Email', models.EmailField(max_length=50)),
                ('Password', models.CharField(max_length=255)),
                ('verification_code', models.IntegerField()),
                ('verified', models.BooleanField(default=False)),
                ('token', models.CharField(max_length=255)),
                ('token_expiry', models.DateTimeField()),
            ],
        ),
    ]
