# Generated by Django 5.0.3 on 2024-03-13 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CO2',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.CharField(max_length=20)),
                ('co2', models.FloatField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
    ]
