# Generated by Django 5.0.3 on 2024-03-13 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_co2'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='co2',
            table='co2',
        ),
    ]
