# Generated by Django 5.0.3 on 2024-03-13 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_co2_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='co2',
            table=None,
        ),
    ]
