# Generated by Django 5.0.3 on 2024-03-15 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_co2_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Facility_Name', models.CharField(max_length=83)),
                ('ODRSF_facility_type', models.CharField(max_length=16)),
                ('Prov_Terr', models.CharField(max_length=7)),
                ('Latitude', models.DecimalField(decimal_places=8, max_digits=10)),
                ('Longitude', models.DecimalField(decimal_places=8, max_digits=11)),
            ],
        ),
    ]
